### ISSUE TITLE
npm run build 无法通过 ， clone下来无法编译， 你们没有遇到吗

### ISSUE THREAD

**Issue by sunbin728** [zhiyicx/plus-component-h5#433]
版本：composer create-project zhiyicx/plus-component-h5:4.0.0-rc.3

Building for production...(node:35463) UnhandledPromiseRejectionWarning: Error: Cyclic dependency
    at visit (/www/wwwroot/plus-component-h5/node_modules/toposort/index.js:35:13)
    at visit (/www/wwwroot/plus-component-h5/node_modules/toposort/index.js:53:9)
    at visit (/www/wwwroot/plus-component-h5/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/www/wwwroot/plus-component-h5/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/www/wwwroot/plus-component-h5/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/www/wwwroot/plus-component-h5/node_modules/html-webpack-plugin/index.js:364:35)
    at /www/wwwroot/plus-component-h5/node_modules/html-webpack-plugin/index.js:113:21
    at _fn0.then._result0 (eval at create (/www/wwwroot/plus-component-h5/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at <anonymous>
(node:35463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35463) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JsonLeex** [comment]
已更新
